# -*- coding: utf-8 -*-
"""Abstract_Class.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OKiN5l1WLFcdOMN5q66lZ42maMmYgWYc
"""

from abc import ABCMeta, abstractmethod
class Book(object, metaclass=ABCMeta):
    def __init__(self,title,author):
        self.title=title
        self.author=author   
    @abstractmethod
    def display(): pass

"""#Write MyBook class"""

class MyBook(Book):
    price=0
    def __init__(self,tittle,author,price):
        super().__init__(tittle,author)
        self.price=price
    def display(self):
        print("Title: "+title)
        print("Author: "+author)
        print("Price: "+str(price))

"""#input"""

title=input()
author=input()
price=int(input())
new_novel=MyBook(title,author,price)
new_novel.display()