# -*- coding: utf-8 -*-
"""Inhertance.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZjrcEamv0td5yQdJ1J4WrcNidvz02bLK
"""

#Base Class Person
class Person:
  def __init__(self, fname, lname):
    self.firstname = fname
    self.lastname = lname

  def printname(self):
    print(self.firstname, self.lastname)

#Derived class
class Student(Person):
  def __init__(self, fname, lname):
    super().__init__(fname, lname)

# Here x is object of class student
x = Student("Sam", "Ram")    #derived class student call
x.printname() #with the object of derived class we are using the property/method of base class